---
- name: Ensure database directory exists
  file:
    path: "{{ db_dir }}"
    state: directory

- name: Build MongoDB database image
  docker_image:
    name: "{{ db_image }}"
    build:
      path: "{{ app_base_dir }}/src/database"
      dockerfile: Dockerfile
    source: build
    state: present
  become: yes

- name: Create MongoDB data volume
  docker_volume:
    name: "{{ db_volume }}"
    state: present
  become: yes

- name: Run MongoDB container
  docker_container:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ db_network }}"
    env: "{{ db_env }}"
    ports:
      - "{{ db_port }}:{{ db_port }}"
    volumes:
      - "{{ db_volume }}:/data/db"
  become: yes